### ISSUE TITLE
Suggestion: Change the timing of screenshot to when the popup appears

### ISSUE THREAD

**Issue by umer-rs** [PJGJ210/Discord-Collection-Logger#1]
At the moment it sends a screenshot instantly after the drop is obtained, missing out the hud popup. Would be real cool if that was included in the pic, runelite auto screenshot already does so. Thanks.

**Comment by PJGJ210** [comment]
This should be fixed in the next update. (https://github.com/runelite/plugin-hub/pull/3237)

pre-update
![image](https://user-images.githubusercontent.com/16944807/186790681-8120fbdc-58e7-4ce6-af14-b911c9ae11fa.png)

post-update
![image](https://user-images.githubusercontent.com/16944807/186792762-cc02b6a7-41ac-46ce-b127-dfef95019893.png)

**Comment by PJGJ210** [comment]
https://github.com/runelite/plugin-hub/pull/3237
Merged. If issue persists re-open.
