### ISSUE TITLE
Typo in Discord notification for getting a pet

### ISSUE THREAD

**Issue by jjccharles** [PJGJ210/Discord-Collection-Logger#2]
Needs an extra space between `received` and `a`

![image](https://user-images.githubusercontent.com/20750727/198165344-d6022f03-962e-4e76-ae46-9e188d094a2d.png)

Quickly had a look at the source code and seems perhaps the issue comes from somewhere upstream? [Could the bug just be temporarily fixed here in the mean time](https://github.com/PJGJ210/Discord-Collection-Logger/blob/master/src/main/java/discordcollectionlogger/DiscordCollectionLoggerPlugin.java#L104)?

Just regex replace that typo with the correction.

**Comment by PJGJ210** [comment]
I do not believe this is my plugin. Instead this is the one below.

If you can confirm it is mine I can look further into it. Since building my plugin I have not received a pet. 

I had identified this issue here

https://github.com/RinZJ/better-discord-loot-logger/blob/3364cf579e4296cf0caf228c633e1652b8380919/src/main/java/com/betterdiscordlootlogger/BetterDiscordLootLoggerPlugin.java#L363

https://github.com/RinZJ/better-discord-loot-logger/issues/9

Thanks for the heads up!
